//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student_Demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFooter1
    {
        public int Id { get; set; }
        public string Displaytext { get; set; }
        public string LinkUrl { get; set; }
        public Nullable<int> SortOrder { get; set; }
    }
}
